name: CML

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[cml]

      - name: Write GDrive credentials to file
        run: |
          mkdir -p .secrets
          echo "${{ secrets.GDRIVE_CREDENTIALS_DATA }}" | base64 --decode > .secrets/dvc-drive-key.json


      - name: Decode GDrive credentials
        run: echo "${{ secrets.GDRIVE_CREDENTIALS_DATA }}" | base64 --decode > gdrive-credentials.json

      - name: Pull data
        run: |
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote gdrive_service_account_json_file_path .secrets/dvc-drive-key.json
          dvc pull

      - name: Run training script
        run: python train.py

      - name: Run CML report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install cml
          cml-send-comment --verbose --json metrics.json

